// Generated by CoffeeScript 1.6.3

  var renderForm, submitForm;

  renderForm = function(hasTitle) {
    var SVGWriteText, contentBox, result, titleBox, widgetFormDiv;
    SVGWriteText = document.getElementById("SVGWriteText");
    widgetFormDiv = document.getElementById("WidgetFormDiv");
    if (SVGWriteText.innerHTML === "Write") {
      SVGWriteText.innerHTML = "Submit";
      titleBox = "Title<br/><input type=\"text\" id=\"title\" name=\"title\"></input><br/>";
      contentBox = "Message</br><textarea id=\"content\" name=\"content\" rows=\"10\"  cols=\"19\"></textarea><br/>";
      result = "";
      if (hasTitle === true) {
        result = titleBox + contentBox;
      } else {
        result = contentBox;
      }
      widgetFormDiv.innerHTML = result;
      
      SVGWriteText.onClick = submitForm();
    }
  };

  submitForm = function() {
    var xhttp;
    xhttp = new XMLHttpRequest();
    xhttp.onreadystatechange = function() {
      var SVGWriteText, widgetFormDiv;
      if (xhttp.readyState === 4 && xhttp.status === 200) {
        SVGWriteText = document.getElementById("SVGWriteTextSubmit");
        widgetFormDiv = document.getElementById("WidgetFormDiv");
        SVGWriteText.visibility = false;
        widgetFormDiv.innerHTML = "";
        sleep(1);
        SVGWriteText.onClick = renderForm(true);
      }
    };
    xhttp.open("POST", "poststory.jsp", true);
    xhttp.send();
    alert("Message sent");
  };
